# Generated by Django 6.0.7 on 2026-07-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = []
